project_id = "zxaaymyuoqdehiyrynnp"

[functions.extract-document]
verify_jwt = false
wall_clock_limit = 300

[functions.mt-sync]
verify_jwt = false

[functions.inbound-sync]
verify_jwt = false

[functions.process-akb-notifications]
verify_jwt = false
